# Generated by Django 2.0.3 on 2018-03-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wybory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wojewodztwo', models.CharField(max_length=30)),
                ('okrag', models.IntegerField()),
                ('gmina', models.CharField(max_length=30)),
                ('powiat', models.CharField(max_length=30)),
                ('obwody', models.IntegerField()),
                ('uprawnieni', models.IntegerField()),
                ('wydane', models.IntegerField()),
                ('oddane', models.IntegerField()),
                ('niewazne', models.IntegerField()),
                ('wazne', models.IntegerField()),
                ('grabowski', models.IntegerField()),
                ('ikonowicz', models.IntegerField()),
                ('kalinowski', models.IntegerField()),
                ('korwin', models.IntegerField()),
                ('krzaklewski', models.IntegerField()),
                ('kwasniewski', models.IntegerField()),
                ('lepper', models.IntegerField()),
                ('lopuszanski', models.IntegerField()),
                ('olechowski', models.IntegerField()),
                ('pawlowski', models.IntegerField()),
                ('walesa', models.IntegerField()),
                ('wilecki', models.IntegerField()),
            ],
        ),
    ]
