# Generated by Django 2.0.3 on 2018-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wybory',
            name='kod_gminy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
