# Generated by Django 2.0.3 on 2018-03-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkw', '0002_wybory_kod_gminy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skrot', models.CharField(max_length=20)),
                ('pelna_godnosc', models.CharField(max_length=50)),
            ],
        ),
    ]
