# Generated by Django 2.0.3 on 2018-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkw', '0003_kandydat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydaci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skrot', models.CharField(max_length=20)),
                ('pelna_godnosc', models.CharField(max_length=50)),
            ],
        ),
    ]
