# Generated by Django 2.0.3 on 2018-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkw', '0004_kandydaci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kandydaci',
        ),
        migrations.RemoveField(
            model_name='kandydat',
            name='id',
        ),
        migrations.AlterField(
            model_name='kandydat',
            name='skrot',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
