# Generated by Django 2.0.3 on 2018-03-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkw', '0005_auto_20180329_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kandydat',
        ),
    ]
