# Generated by Django 2.0.3 on 2018-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkw', '0006_delete_kandydat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('skrot', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pelna_godnosc', models.CharField(max_length=50)),
            ],
        ),
    ]
