# Generated by Django 2.0.3 on 2018-03-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkw', '0007_kandydat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Okregi',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=20)),
            ],
        ),
    ]
