# Generated by Django 2.0.3 on 2018-03-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkw', '0008_okregi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wybory',
            old_name='okrag',
            new_name='okreg',
        ),
    ]
